const image = require("./tools/image")
const video = require("./tools/video")
const loader = require("./tools/loader")
const server = require("./tools/server")
const minify = require("./tools/minify")
const mute = require("./tools/mute")
const snow = require("./tools/snow")
const matrix = require("./tools/matrix")
module.exports.image = image
module.exports.loader = loader
module.exports.video = video
module.exports.server = server
module.exports.minify = minify
module.exports.muter = mute
module.exports.snow = snow
module.exports.matrix = matrix
